services:
  nginx:
    image: nginx:1.25.5-alpine
    restart: unless-stopped
    volumes:
     - ./docker-data/certbot/conf:/etc/letsencrypt
     - ./docker-data/certbot/www:/usr/share/nginx/html/
    ports:
     - "${HTTP_PORT}:80"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./docker-data/certbot/conf:/etc/letsencrypt
      - ./docker-data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
